"""empty message

Revision ID: 36b41e9128de
Revises: d906103fb479
Create Date: 2018-10-19 21:40:32.502866

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '36b41e9128de'
down_revision = 'd906103fb479'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_examrequest_accommodations'), 'examrequest', ['accommodations'], unique=False)
    op.create_index(op.f('ix_examrequest_course_id'), 'examrequest', ['course_id'], unique=False)
    op.create_index(op.f('ix_examrequest_course_name'), 'examrequest', ['course_name'], unique=False)
    op.create_index(op.f('ix_examrequest_csd_building'), 'examrequest', ['csd_building'], unique=False)
    op.create_index(op.f('ix_examrequest_csd_campus'), 'examrequest', ['csd_campus'], unique=False)
    op.create_index(op.f('ix_examrequest_csd_room'), 'examrequest', ['csd_room'], unique=False)
    op.create_index(op.f('ix_examrequest_csd_seat'), 'examrequest', ['csd_seat'], unique=False)
    op.create_index(op.f('ix_examrequest_exam_csd_time'), 'examrequest', ['exam_csd_time'], unique=False)
    op.create_index(op.f('ix_examrequest_exam_format'), 'examrequest', ['exam_format'], unique=False)
    op.create_index(op.f('ix_examrequest_exam_time'), 'examrequest', ['exam_time'], unique=False)
    op.create_index(op.f('ix_examrequest_exam_type'), 'examrequest', ['exam_type'], unique=False)
    op.create_index(op.f('ix_examrequest_instructor_email'), 'examrequest', ['instructor_email'], unique=False)
    op.create_index(op.f('ix_examrequest_instructor_name'), 'examrequest', ['instructor_name'], unique=False)
    op.create_index(op.f('ix_examrequest_instructor_netid'), 'examrequest', ['instructor_netid'], unique=False)
    op.create_index(op.f('ix_examrequest_instructor_notes'), 'examrequest', ['instructor_notes'], unique=False)
    op.create_index(op.f('ix_examrequest_instructor_phone'), 'examrequest', ['instructor_phone'], unique=False)
    op.create_index(op.f('ix_examrequest_material'), 'examrequest', ['material'], unique=False)
    op.create_index(op.f('ix_examrequest_student_id'), 'examrequest', ['student_id'], unique=False)
    op.create_index(op.f('ix_examrequest_student_name'), 'examrequest', ['student_name'], unique=False)
    op.create_index(op.f('ix_examrequest_student_netid'), 'examrequest', ['student_netid'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_examrequest_student_netid'), table_name='examrequest')
    op.drop_index(op.f('ix_examrequest_student_name'), table_name='examrequest')
    op.drop_index(op.f('ix_examrequest_student_id'), table_name='examrequest')
    op.drop_index(op.f('ix_examrequest_material'), table_name='examrequest')
    op.drop_index(op.f('ix_examrequest_instructor_phone'), table_name='examrequest')
    op.drop_index(op.f('ix_examrequest_instructor_notes'), table_name='examrequest')
    op.drop_index(op.f('ix_examrequest_instructor_netid'), table_name='examrequest')
    op.drop_index(op.f('ix_examrequest_instructor_name'), table_name='examrequest')
    op.drop_index(op.f('ix_examrequest_instructor_email'), table_name='examrequest')
    op.drop_index(op.f('ix_examrequest_exam_type'), table_name='examrequest')
    op.drop_index(op.f('ix_examrequest_exam_time'), table_name='examrequest')
    op.drop_index(op.f('ix_examrequest_exam_format'), table_name='examrequest')
    op.drop_index(op.f('ix_examrequest_exam_csd_time'), table_name='examrequest')
    op.drop_index(op.f('ix_examrequest_csd_seat'), table_name='examrequest')
    op.drop_index(op.f('ix_examrequest_csd_room'), table_name='examrequest')
    op.drop_index(op.f('ix_examrequest_csd_campus'), table_name='examrequest')
    op.drop_index(op.f('ix_examrequest_csd_building'), table_name='examrequest')
    op.drop_index(op.f('ix_examrequest_course_name'), table_name='examrequest')
    op.drop_index(op.f('ix_examrequest_course_id'), table_name='examrequest')
    op.drop_index(op.f('ix_examrequest_accommodations'), table_name='examrequest')
    # ### end Alembic commands ###
