"""exam requests

Revision ID: d906103fb479
Revises: 
Create Date: 2018-10-19 21:12:29.852248

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd906103fb479'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('examrequest',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=True),
    sa.Column('student_netid', sa.String(length=120), nullable=True),
    sa.Column('student_name', sa.String(length=120), nullable=True),
    sa.Column('course_id', sa.String(length=120), nullable=True),
    sa.Column('course_name', sa.String(length=120), nullable=True),
    sa.Column('exam_type', sa.String(length=120), nullable=True),
    sa.Column('exam_format', sa.String(length=120), nullable=True),
    sa.Column('exam_time', sa.String(length=120), nullable=True),
    sa.Column('exam_csd_time', sa.String(length=120), nullable=True),
    sa.Column('csd_campus', sa.String(length=120), nullable=True),
    sa.Column('csd_building', sa.String(length=120), nullable=True),
    sa.Column('csd_room', sa.String(length=120), nullable=True),
    sa.Column('csd_seat', sa.String(length=120), nullable=True),
    sa.Column('instructor_netid', sa.String(length=120), nullable=True),
    sa.Column('instructor_name', sa.String(length=120), nullable=True),
    sa.Column('instructor_phone', sa.String(length=120), nullable=True),
    sa.Column('instructor_email', sa.String(length=120), nullable=True),
    sa.Column('material', sa.String(length=120), nullable=True),
    sa.Column('accommodations', sa.String(length=120), nullable=True),
    sa.Column('instructor_notes', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('examrequest')
    # ### end Alembic commands ###
